Running tasks:   0% |                                          | ETA:  --:--:--
Detected E3SM supported machine: chicoma-cpu
Using the following config files:
   /users/vankova/mpas-analysis/fris_map2/mpas_analysis/default.cfg
   /users/vankova/miniconda3/envs/mpas_dev/lib/python3.11/site-packages/mache/machines/chicoma-cpu.cfg
   /users/vankova/mpas-analysis/fris_map2/mpas_analysis/configuration/chicoma-cpu.cfg
   /users/vankova/mpas-analysis/fris_map2/mpas_analysis/__main__.py
   /users/vankova/mpas-analysis/fris_map2/cfg_files/sorrmGcases/chic_e3sm_test_00_30.cfg
copying /users/vankova/mpas-analysis/fris_map2/cfg_files/sorrmGcases/chic_e3sm_test_00_30.cfg to HTML dir.

Traceback (most recent call last):
  File "/users/vankova/mpas-analysis/fris_map2/mpas_analysis/__main__.py", line 445, in add_task_and_subtasks
    analysisTask.setup_and_check()
  File "/users/vankova/mpas-analysis/fris_map2/mpas_analysis/shared/climatology/mpas_climatology_task.py", line 279, in setup_and_check
    self.inputFiles = self.historyStreams.readpath(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/users/vankova/mpas-analysis/fris_map2/mpas_analysis/shared/io/namelist_streams_interface.py", line 445, in readpath
    startDate = string_to_datetime(startDate)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/users/vankova/mpas-analysis/fris_map2/mpas_analysis/shared/timekeeping/utility.py", line 111, in string_to_datetime
    return datetime.datetime(year=year, month=month, day=day, hour=hour,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: year 0 is out of range
Warning: mpasClimatologyOceanAvg failed during check and will not be run
Traceback (most recent call last):
  File "/users/vankova/mpas-analysis/fris_map2/mpas_analysis/__main__.py", line 445, in add_task_and_subtasks
    analysisTask.setup_and_check()
  File "/users/vankova/mpas-analysis/fris_map2/mpas_analysis/shared/climatology/mpas_climatology_task.py", line 279, in setup_and_check
    self.inputFiles = self.historyStreams.readpath(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/users/vankova/mpas-analysis/fris_map2/mpas_analysis/shared/io/namelist_streams_interface.py", line 445, in readpath
    startDate = string_to_datetime(startDate)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/users/vankova/mpas-analysis/fris_map2/mpas_analysis/shared/timekeeping/utility.py", line 111, in string_to_datetime
    return datetime.datetime(year=year, month=month, day=day, hour=hour,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: year 0 is out of range
Warning: mpasClimatologyOceanAvg failed during check and will not be run
Warning: prerequisite of climatologyMapMLD failed during check, so this task will not be run
Traceback (most recent call last):
  File "/users/vankova/mpas-analysis/fris_map2/mpas_analysis/__main__.py", line 445, in add_task_and_subtasks
    analysisTask.setup_and_check()
  File "/users/vankova/mpas-analysis/fris_map2/mpas_analysis/shared/climatology/mpas_climatology_task.py", line 279, in setup_and_check
    self.inputFiles = self.historyStreams.readpath(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/users/vankova/mpas-analysis/fris_map2/mpas_analysis/shared/io/namelist_streams_interface.py", line 445, in readpath
    startDate = string_to_datetime(startDate)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/users/vankova/mpas-analysis/fris_map2/mpas_analysis/shared/timekeeping/utility.py", line 111, in string_to_datetime
    return datetime.datetime(year=year, month=month, day=day, hour=hour,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: year 0 is out of range
Warning: mpasClimatologyOceanAvg failed during check and will not be run
Warning: prerequisite of climatologyMapSST failed during check, so this task will not be run
Traceback (most recent call last):
  File "/users/vankova/mpas-analysis/fris_map2/mpas_analysis/__main__.py", line 445, in add_task_and_subtasks
    analysisTask.setup_and_check()
  File "/users/vankova/mpas-analysis/fris_map2/mpas_analysis/shared/climatology/mpas_climatology_task.py", line 279, in setup_and_check
    self.inputFiles = self.historyStreams.readpath(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/users/vankova/mpas-analysis/fris_map2/mpas_analysis/shared/io/namelist_streams_interface.py", line 445, in readpath
    startDate = string_to_datetime(startDate)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/users/vankova/mpas-analysis/fris_map2/mpas_analysis/shared/timekeeping/utility.py", line 111, in string_to_datetime
    return datetime.datetime(year=year, month=month, day=day, hour=hour,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: year 0 is out of range
Warning: mpasClimatologyOceanAvg failed during check and will not be run
Warning: prerequisite of climatologyMapSSS failed during check, so this task will not be run
Traceback (most recent call last):
  File "/users/vankova/mpas-analysis/fris_map2/mpas_analysis/__main__.py", line 445, in add_task_and_subtasks
    analysisTask.setup_and_check()
  File "/users/vankova/mpas-analysis/fris_map2/mpas_analysis/shared/climatology/mpas_climatology_task.py", line 279, in setup_and_check
    self.inputFiles = self.historyStreams.readpath(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/users/vankova/mpas-analysis/fris_map2/mpas_analysis/shared/io/namelist_streams_interface.py", line 445, in readpath
    startDate = string_to_datetime(startDate)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/users/vankova/mpas-analysis/fris_map2/mpas_analysis/shared/timekeeping/utility.py", line 111, in string_to_datetime
    return datetime.datetime(year=year, month=month, day=day, hour=hour,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: year 0 is out of range
Warning: mpasClimatologyOceanAvg failed during check and will not be run
Warning: prerequisite of climatologyMapSSH failed during check, so this task will not be run
Traceback (most recent call last):
  File "/users/vankova/mpas-analysis/fris_map2/mpas_analysis/__main__.py", line 445, in add_task_and_subtasks
    analysisTask.setup_and_check()
  File "/users/vankova/mpas-analysis/fris_map2/mpas_analysis/shared/climatology/mpas_climatology_task.py", line 279, in setup_and_check
    self.inputFiles = self.historyStreams.readpath(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/users/vankova/mpas-analysis/fris_map2/mpas_analysis/shared/io/namelist_streams_interface.py", line 445, in readpath
    startDate = string_to_datetime(startDate)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/users/vankova/mpas-analysis/fris_map2/mpas_analysis/shared/timekeeping/utility.py", line 111, in string_to_datetime
    return datetime.datetime(year=year, month=month, day=day, hour=hour,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: year 0 is out of range
Warning: mpasClimatologyOceanAvg failed during check and will not be run
Warning: prerequisite of climatologyMapEKE failed during check, so this task will not be run
Traceback (most recent call last):
  File "/users/vankova/mpas-analysis/fris_map2/mpas_analysis/__main__.py", line 445, in add_task_and_subtasks
    analysisTask.setup_and_check()
  File "/users/vankova/mpas-analysis/fris_map2/mpas_analysis/shared/climatology/mpas_climatology_task.py", line 279, in setup_and_check
    self.inputFiles = self.historyStreams.readpath(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/users/vankova/mpas-analysis/fris_map2/mpas_analysis/shared/io/namelist_streams_interface.py", line 445, in readpath
    startDate = string_to_datetime(startDate)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/users/vankova/mpas-analysis/fris_map2/mpas_analysis/shared/timekeeping/utility.py", line 111, in string_to_datetime
    return datetime.datetime(year=year, month=month, day=day, hour=hour,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: year 0 is out of range
Warning: mpasClimatologyOceanAvg failed during check and will not be run
Warning: prerequisite of climatologyMapBSF failed during check, so this task will not be run
Traceback (most recent call last):
  File "/users/vankova/mpas-analysis/fris_map2/mpas_analysis/__main__.py", line 445, in add_task_and_subtasks
    analysisTask.setup_and_check()
  File "/users/vankova/mpas-analysis/fris_map2/mpas_analysis/shared/climatology/mpas_climatology_task.py", line 279, in setup_and_check
    self.inputFiles = self.historyStreams.readpath(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/users/vankova/mpas-analysis/fris_map2/mpas_analysis/shared/io/namelist_streams_interface.py", line 445, in readpath
    startDate = string_to_datetime(startDate)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/users/vankova/mpas-analysis/fris_map2/mpas_analysis/shared/timekeeping/utility.py", line 111, in string_to_datetime
    return datetime.datetime(year=year, month=month, day=day, hour=hour,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: year 0 is out of range
Warning: mpasClimatologyOceanAvg failed during check and will not be run
Warning: prerequisite of climatologyMapOHCAnomaly failed during check, so this task will not be run
Traceback (most recent call last):
  File "/users/vankova/mpas-analysis/fris_map2/mpas_analysis/__main__.py", line 445, in add_task_and_subtasks
    analysisTask.setup_and_check()
  File "/users/vankova/mpas-analysis/fris_map2/mpas_analysis/shared/climatology/mpas_climatology_task.py", line 279, in setup_and_check
    self.inputFiles = self.historyStreams.readpath(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/users/vankova/mpas-analysis/fris_map2/mpas_analysis/shared/io/namelist_streams_interface.py", line 445, in readpath
    startDate = string_to_datetime(startDate)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/users/vankova/mpas-analysis/fris_map2/mpas_analysis/shared/timekeeping/utility.py", line 111, in string_to_datetime
    return datetime.datetime(year=year, month=month, day=day, hour=hour,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: year 0 is out of range
Warning: mpasClimatologyOceanAvg failed during check and will not be run
Warning: prerequisite of climatologyMapSose failed during check, so this task will not be run
Traceback (most recent call last):
  File "/users/vankova/mpas-analysis/fris_map2/mpas_analysis/__main__.py", line 445, in add_task_and_subtasks
    analysisTask.setup_and_check()
  File "/users/vankova/mpas-analysis/fris_map2/mpas_analysis/shared/climatology/mpas_climatology_task.py", line 279, in setup_and_check
    self.inputFiles = self.historyStreams.readpath(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/users/vankova/mpas-analysis/fris_map2/mpas_analysis/shared/io/namelist_streams_interface.py", line 445, in readpath
    startDate = string_to_datetime(startDate)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/users/vankova/mpas-analysis/fris_map2/mpas_analysis/shared/timekeeping/utility.py", line 111, in string_to_datetime
    return datetime.datetime(year=year, month=month, day=day, hour=hour,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: year 0 is out of range
Warning: mpasClimatologyOceanAvg failed during check and will not be run
Warning: prerequisite of climatologyMapWoa failed during check, so this task will not be run
Traceback (most recent call last):
  File "/users/vankova/mpas-analysis/fris_map2/mpas_analysis/__main__.py", line 445, in add_task_and_subtasks
    analysisTask.setup_and_check()
  File "/users/vankova/mpas-analysis/fris_map2/mpas_analysis/shared/climatology/mpas_climatology_task.py", line 279, in setup_and_check
    self.inputFiles = self.historyStreams.readpath(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/users/vankova/mpas-analysis/fris_map2/mpas_analysis/shared/io/namelist_streams_interface.py", line 445, in readpath
    startDate = string_to_datetime(startDate)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/users/vankova/mpas-analysis/fris_map2/mpas_analysis/shared/timekeeping/utility.py", line 111, in string_to_datetime
    return datetime.datetime(year=year, month=month, day=day, hour=hour,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: year 0 is out of range
Warning: mpasClimatologyOceanAvg failed during check and will not be run
Warning: prerequisite of climatologyMapArgoTemperature failed during check, so this task will not be run
Traceback (most recent call last):
  File "/users/vankova/mpas-analysis/fris_map2/mpas_analysis/__main__.py", line 445, in add_task_and_subtasks
    analysisTask.setup_and_check()
  File "/users/vankova/mpas-analysis/fris_map2/mpas_analysis/shared/climatology/mpas_climatology_task.py", line 279, in setup_and_check
    self.inputFiles = self.historyStreams.readpath(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/users/vankova/mpas-analysis/fris_map2/mpas_analysis/shared/io/namelist_streams_interface.py", line 445, in readpath
    startDate = string_to_datetime(startDate)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/users/vankova/mpas-analysis/fris_map2/mpas_analysis/shared/timekeeping/utility.py", line 111, in string_to_datetime
    return datetime.datetime(year=year, month=month, day=day, hour=hour,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: year 0 is out of range
Warning: mpasClimatologyOceanAvg failed during check and will not be run
Warning: prerequisite of climatologyMapArgoSalinity failed during check, so this task will not be run
Traceback (most recent call last):
  File "/users/vankova/mpas-analysis/fris_map2/mpas_analysis/__main__.py", line 445, in add_task_and_subtasks
    analysisTask.setup_and_check()
  File "/users/vankova/mpas-analysis/fris_map2/mpas_analysis/shared/climatology/mpas_climatology_task.py", line 279, in setup_and_check
    self.inputFiles = self.historyStreams.readpath(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/users/vankova/mpas-analysis/fris_map2/mpas_analysis/shared/io/namelist_streams_interface.py", line 445, in readpath
    startDate = string_to_datetime(startDate)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/users/vankova/mpas-analysis/fris_map2/mpas_analysis/shared/timekeeping/utility.py", line 111, in string_to_datetime
    return datetime.datetime(year=year, month=month, day=day, hour=hour,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: year 0 is out of range
Warning: mpasClimatologyOceanAvg failed during check and will not be run
Warning: prerequisite of climatologyMapSchmidtko failed during check, so this task will not be run
Traceback (most recent call last):
  File "/users/vankova/mpas-analysis/fris_map2/mpas_analysis/__main__.py", line 445, in add_task_and_subtasks
    analysisTask.setup_and_check()
  File "/users/vankova/mpas-analysis/fris_map2/mpas_analysis/shared/climatology/mpas_climatology_task.py", line 279, in setup_and_check
    self.inputFiles = self.historyStreams.readpath(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/users/vankova/mpas-analysis/fris_map2/mpas_analysis/shared/io/namelist_streams_interface.py", line 445, in readpath
    startDate = string_to_datetime(startDate)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/users/vankova/mpas-analysis/fris_map2/mpas_analysis/shared/timekeeping/utility.py", line 111, in string_to_datetime
    return datetime.datetime(year=year, month=month, day=day, hour=hour,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: year 0 is out of range
Warning: mpasClimatologyOceanAvg failed during check and will not be run
Warning: prerequisite of climatologyMapAntarcticMelt failed during check, so this task will not be run
Traceback (most recent call last):
  File "/users/vankova/mpas-analysis/fris_map2/mpas_analysis/__main__.py", line 445, in add_task_and_subtasks
    analysisTask.setup_and_check()
  File "/users/vankova/mpas-analysis/fris_map2/mpas_analysis/shared/climatology/mpas_climatology_task.py", line 279, in setup_and_check
    self.inputFiles = self.historyStreams.readpath(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/users/vankova/mpas-analysis/fris_map2/mpas_analysis/shared/io/namelist_streams_interface.py", line 445, in readpath
    startDate = string_to_datetime(startDate)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/users/vankova/mpas-analysis/fris_map2/mpas_analysis/shared/timekeeping/utility.py", line 111, in string_to_datetime
    return datetime.datetime(year=year, month=month, day=day, hour=hour,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: year 0 is out of range
Warning: mpasClimatologyOceanAvg failed during check and will not be run
Warning: prerequisite of regionalTSDiagrams failed during check, so this task will not be run
Traceback (most recent call last):
  File "/users/vankova/mpas-analysis/fris_map2/mpas_analysis/__main__.py", line 445, in add_task_and_subtasks
    analysisTask.setup_and_check()
  File "/users/vankova/mpas-analysis/fris_map2/mpas_analysis/shared/time_series/mpas_time_series_task.py", line 174, in setup_and_check
    self.inputFiles = self.historyStreams.readpath(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/users/vankova/mpas-analysis/fris_map2/mpas_analysis/shared/io/namelist_streams_interface.py", line 445, in readpath
    startDate = string_to_datetime(startDate)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/users/vankova/mpas-analysis/fris_map2/mpas_analysis/shared/timekeeping/utility.py", line 111, in string_to_datetime
    return datetime.datetime(year=year, month=month, day=day, hour=hour,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: year 0 is out of range
Warning: mpasTimeSeriesOcean failed during check and will not be run
Warning: prerequisite of timeSeriesAntarcticMelt failed during check, so this task will not be run
Traceback (most recent call last):
  File "/users/vankova/mpas-analysis/fris_map2/mpas_analysis/__main__.py", line 445, in add_task_and_subtasks
    analysisTask.setup_and_check()
  File "/users/vankova/mpas-analysis/fris_map2/mpas_analysis/shared/time_series/mpas_time_series_task.py", line 174, in setup_and_check
    self.inputFiles = self.historyStreams.readpath(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/users/vankova/mpas-analysis/fris_map2/mpas_analysis/shared/io/namelist_streams_interface.py", line 445, in readpath
    startDate = string_to_datetime(startDate)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/users/vankova/mpas-analysis/fris_map2/mpas_analysis/shared/timekeeping/utility.py", line 111, in string_to_datetime
    return datetime.datetime(year=year, month=month, day=day, hour=hour,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: year 0 is out of range
Warning: mpasTimeSeriesOcean failed during check and will not be run
Warning: prerequisite of timeSeriesTemperatureAnomaly failed during check, so this task will not be run
Traceback (most recent call last):
  File "/users/vankova/mpas-analysis/fris_map2/mpas_analysis/__main__.py", line 445, in add_task_and_subtasks
    analysisTask.setup_and_check()
  File "/users/vankova/mpas-analysis/fris_map2/mpas_analysis/shared/time_series/mpas_time_series_task.py", line 174, in setup_and_check
    self.inputFiles = self.historyStreams.readpath(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/users/vankova/mpas-analysis/fris_map2/mpas_analysis/shared/io/namelist_streams_interface.py", line 445, in readpath
    startDate = string_to_datetime(startDate)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/users/vankova/mpas-analysis/fris_map2/mpas_analysis/shared/timekeeping/utility.py", line 111, in string_to_datetime
    return datetime.datetime(year=year, month=month, day=day, hour=hour,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: year 0 is out of range
Warning: mpasTimeSeriesOcean failed during check and will not be run
Warning: prerequisite of timeSeriesSalinityAnomaly failed during check, so this task will not be run
Traceback (most recent call last):
  File "/users/vankova/mpas-analysis/fris_map2/mpas_analysis/__main__.py", line 445, in add_task_and_subtasks
    analysisTask.setup_and_check()
  File "/users/vankova/mpas-analysis/fris_map2/mpas_analysis/shared/time_series/mpas_time_series_task.py", line 174, in setup_and_check
    self.inputFiles = self.historyStreams.readpath(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/users/vankova/mpas-analysis/fris_map2/mpas_analysis/shared/io/namelist_streams_interface.py", line 445, in readpath
    startDate = string_to_datetime(startDate)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/users/vankova/mpas-analysis/fris_map2/mpas_analysis/shared/timekeeping/utility.py", line 111, in string_to_datetime
    return datetime.datetime(year=year, month=month, day=day, hour=hour,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: year 0 is out of range
Warning: mpasTimeSeriesOcean failed during check and will not be run
Warning: prerequisite of timeSeriesOHCAnomaly failed during check, so this task will not be run
Traceback (most recent call last):
  File "/users/vankova/mpas-analysis/fris_map2/mpas_analysis/__main__.py", line 445, in add_task_and_subtasks
    analysisTask.setup_and_check()
  File "/users/vankova/mpas-analysis/fris_map2/mpas_analysis/shared/time_series/mpas_time_series_task.py", line 174, in setup_and_check
    self.inputFiles = self.historyStreams.readpath(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/users/vankova/mpas-analysis/fris_map2/mpas_analysis/shared/io/namelist_streams_interface.py", line 445, in readpath
    startDate = string_to_datetime(startDate)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/users/vankova/mpas-analysis/fris_map2/mpas_analysis/shared/timekeeping/utility.py", line 111, in string_to_datetime
    return datetime.datetime(year=year, month=month, day=day, hour=hour,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: year 0 is out of range
Warning: mpasTimeSeriesOcean failed during check and will not be run
Warning: prerequisite of timeSeriesSSHAnomaly failed during check, so this task will not be run
Traceback (most recent call last):
  File "/users/vankova/mpas-analysis/fris_map2/mpas_analysis/__main__.py", line 445, in add_task_and_subtasks
    analysisTask.setup_and_check()
  File "/users/vankova/mpas-analysis/fris_map2/mpas_analysis/shared/time_series/mpas_time_series_task.py", line 174, in setup_and_check
    self.inputFiles = self.historyStreams.readpath(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/users/vankova/mpas-analysis/fris_map2/mpas_analysis/shared/io/namelist_streams_interface.py", line 445, in readpath
    startDate = string_to_datetime(startDate)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/users/vankova/mpas-analysis/fris_map2/mpas_analysis/shared/timekeeping/utility.py", line 111, in string_to_datetime
    return datetime.datetime(year=year, month=month, day=day, hour=hour,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: year 0 is out of range
Warning: mpasTimeSeriesOcean failed during check and will not be run
Warning: prerequisite of timeSeriesSST failed during check, so this task will not be run
Traceback (most recent call last):
  File "/users/vankova/mpas-analysis/fris_map2/mpas_analysis/__main__.py", line 445, in add_task_and_subtasks
    analysisTask.setup_and_check()
  File "/users/vankova/mpas-analysis/fris_map2/mpas_analysis/shared/climatology/mpas_climatology_task.py", line 279, in setup_and_check
    self.inputFiles = self.historyStreams.readpath(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/users/vankova/mpas-analysis/fris_map2/mpas_analysis/shared/io/namelist_streams_interface.py", line 445, in readpath
    startDate = string_to_datetime(startDate)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/users/vankova/mpas-analysis/fris_map2/mpas_analysis/shared/timekeeping/utility.py", line 111, in string_to_datetime
    return datetime.datetime(year=year, month=month, day=day, hour=hour,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: year 0 is out of range
Warning: mpasClimatologyOceanAvg failed during check and will not be run
Warning: prerequisite of oceanHistogram failed during check, so this task will not be run
Traceback (most recent call last):
  File "/users/vankova/mpas-analysis/fris_map2/mpas_analysis/__main__.py", line 445, in add_task_and_subtasks
    analysisTask.setup_and_check()
  File "/users/vankova/mpas-analysis/fris_map2/mpas_analysis/shared/climatology/mpas_climatology_task.py", line 279, in setup_and_check
    self.inputFiles = self.historyStreams.readpath(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/users/vankova/mpas-analysis/fris_map2/mpas_analysis/shared/io/namelist_streams_interface.py", line 445, in readpath
    startDate = string_to_datetime(startDate)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/users/vankova/mpas-analysis/fris_map2/mpas_analysis/shared/timekeeping/utility.py", line 111, in string_to_datetime
    return datetime.datetime(year=year, month=month, day=day, hour=hour,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: year 0 is out of range
Warning: mpasClimatologyOceanAvg failed during check and will not be run
Warning: prerequisite of meridionalHeatTransport failed during check, so this task will not be run
Traceback (most recent call last):
  File "/users/vankova/mpas-analysis/fris_map2/mpas_analysis/__main__.py", line 445, in add_task_and_subtasks
    analysisTask.setup_and_check()
  File "/users/vankova/mpas-analysis/fris_map2/mpas_analysis/shared/climatology/mpas_climatology_task.py", line 279, in setup_and_check
    self.inputFiles = self.historyStreams.readpath(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/users/vankova/mpas-analysis/fris_map2/mpas_analysis/shared/io/namelist_streams_interface.py", line 445, in readpath
    startDate = string_to_datetime(startDate)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/users/vankova/mpas-analysis/fris_map2/mpas_analysis/shared/timekeeping/utility.py", line 111, in string_to_datetime
    return datetime.datetime(year=year, month=month, day=day, hour=hour,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: year 0 is out of range
Warning: mpasClimatologyOceanAvg failed during check and will not be run
Warning: prerequisite of woceTransects failed during check, so this task will not be run
Traceback (most recent call last):
  File "/users/vankova/mpas-analysis/fris_map2/mpas_analysis/__main__.py", line 445, in add_task_and_subtasks
    analysisTask.setup_and_check()
  File "/users/vankova/mpas-analysis/fris_map2/mpas_analysis/shared/climatology/mpas_climatology_task.py", line 279, in setup_and_check
    self.inputFiles = self.historyStreams.readpath(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/users/vankova/mpas-analysis/fris_map2/mpas_analysis/shared/io/namelist_streams_interface.py", line 445, in readpath
    startDate = string_to_datetime(startDate)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/users/vankova/mpas-analysis/fris_map2/mpas_analysis/shared/timekeeping/utility.py", line 111, in string_to_datetime
    return datetime.datetime(year=year, month=month, day=day, hour=hour,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: year 0 is out of range
Warning: mpasClimatologyOceanAvg failed during check and will not be run
Warning: prerequisite of soseTransects failed during check, so this task will not be run
Traceback (most recent call last):
  File "/users/vankova/mpas-analysis/fris_map2/mpas_analysis/__main__.py", line 445, in add_task_and_subtasks
    analysisTask.setup_and_check()
  File "/users/vankova/mpas-analysis/fris_map2/mpas_analysis/shared/climatology/mpas_climatology_task.py", line 279, in setup_and_check
    self.inputFiles = self.historyStreams.readpath(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/users/vankova/mpas-analysis/fris_map2/mpas_analysis/shared/io/namelist_streams_interface.py", line 445, in readpath
    startDate = string_to_datetime(startDate)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/users/vankova/mpas-analysis/fris_map2/mpas_analysis/shared/timekeeping/utility.py", line 111, in string_to_datetime
    return datetime.datetime(year=year, month=month, day=day, hour=hour,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: year 0 is out of range
Warning: mpasClimatologySeaIceAvg failed during check and will not be run
Traceback (most recent call last):
  File "/users/vankova/mpas-analysis/fris_map2/mpas_analysis/__main__.py", line 445, in add_task_and_subtasks
    analysisTask.setup_and_check()
  File "/users/vankova/mpas-analysis/fris_map2/mpas_analysis/shared/climatology/mpas_climatology_task.py", line 279, in setup_and_check
    self.inputFiles = self.historyStreams.readpath(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/users/vankova/mpas-analysis/fris_map2/mpas_analysis/shared/io/namelist_streams_interface.py", line 445, in readpath
    startDate = string_to_datetime(startDate)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/users/vankova/mpas-analysis/fris_map2/mpas_analysis/shared/timekeeping/utility.py", line 111, in string_to_datetime
    return datetime.datetime(year=year, month=month, day=day, hour=hour,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: year 0 is out of range
Warning: mpasClimatologySeaIceAvg failed during check and will not be run
Warning: prerequisite of climatologyMapSeaIceConcNH failed during check, so this task will not be run
Traceback (most recent call last):
  File "/users/vankova/mpas-analysis/fris_map2/mpas_analysis/__main__.py", line 445, in add_task_and_subtasks
    analysisTask.setup_and_check()
  File "/users/vankova/mpas-analysis/fris_map2/mpas_analysis/shared/climatology/mpas_climatology_task.py", line 279, in setup_and_check
    self.inputFiles = self.historyStreams.readpath(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/users/vankova/mpas-analysis/fris_map2/mpas_analysis/shared/io/namelist_streams_interface.py", line 445, in readpath
    startDate = string_to_datetime(startDate)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/users/vankova/mpas-analysis/fris_map2/mpas_analysis/shared/timekeeping/utility.py", line 111, in string_to_datetime
    return datetime.datetime(year=year, month=month, day=day, hour=hour,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: year 0 is out of range
Warning: mpasClimatologySeaIceAvg failed during check and will not be run
Warning: prerequisite of climatologyMapSeaIceThickNH failed during check, so this task will not be run
Traceback (most recent call last):
  File "/users/vankova/mpas-analysis/fris_map2/mpas_analysis/__main__.py", line 445, in add_task_and_subtasks
    analysisTask.setup_and_check()
  File "/users/vankova/mpas-analysis/fris_map2/mpas_analysis/shared/climatology/mpas_climatology_task.py", line 279, in setup_and_check
    self.inputFiles = self.historyStreams.readpath(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/users/vankova/mpas-analysis/fris_map2/mpas_analysis/shared/io/namelist_streams_interface.py", line 445, in readpath
    startDate = string_to_datetime(startDate)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/users/vankova/mpas-analysis/fris_map2/mpas_analysis/shared/timekeeping/utility.py", line 111, in string_to_datetime
    return datetime.datetime(year=year, month=month, day=day, hour=hour,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: year 0 is out of range
Warning: mpasClimatologySeaIceAvg failed during check and will not be run
Warning: prerequisite of climatologyMapSeaIceConcSH failed during check, so this task will not be run
Traceback (most recent call last):
  File "/users/vankova/mpas-analysis/fris_map2/mpas_analysis/__main__.py", line 445, in add_task_and_subtasks
    analysisTask.setup_and_check()
  File "/users/vankova/mpas-analysis/fris_map2/mpas_analysis/shared/climatology/mpas_climatology_task.py", line 279, in setup_and_check
    self.inputFiles = self.historyStreams.readpath(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/users/vankova/mpas-analysis/fris_map2/mpas_analysis/shared/io/namelist_streams_interface.py", line 445, in readpath
    startDate = string_to_datetime(startDate)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/users/vankova/mpas-analysis/fris_map2/mpas_analysis/shared/timekeeping/utility.py", line 111, in string_to_datetime
    return datetime.datetime(year=year, month=month, day=day, hour=hour,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: year 0 is out of range
Warning: mpasClimatologySeaIceAvg failed during check and will not be run
Warning: prerequisite of climatologyMapSeaIceThickSH failed during check, so this task will not be run
Traceback (most recent call last):
  File "/users/vankova/mpas-analysis/fris_map2/mpas_analysis/__main__.py", line 445, in add_task_and_subtasks
    analysisTask.setup_and_check()
  File "/users/vankova/mpas-analysis/fris_map2/mpas_analysis/shared/time_series/mpas_time_series_task.py", line 174, in setup_and_check
    self.inputFiles = self.historyStreams.readpath(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/users/vankova/mpas-analysis/fris_map2/mpas_analysis/shared/io/namelist_streams_interface.py", line 445, in readpath
    startDate = string_to_datetime(startDate)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/users/vankova/mpas-analysis/fris_map2/mpas_analysis/shared/timekeeping/utility.py", line 111, in string_to_datetime
    return datetime.datetime(year=year, month=month, day=day, hour=hour,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: year 0 is out of range
Warning: mpasTimeSeriesSeaIce failed during check and will not be run
Traceback (most recent call last):
  File "/users/vankova/mpas-analysis/fris_map2/mpas_analysis/__main__.py", line 445, in add_task_and_subtasks
    analysisTask.setup_and_check()
  File "/users/vankova/mpas-analysis/fris_map2/mpas_analysis/shared/climatology/mpas_climatology_task.py", line 279, in setup_and_check
    self.inputFiles = self.historyStreams.readpath(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/users/vankova/mpas-analysis/fris_map2/mpas_analysis/shared/io/namelist_streams_interface.py", line 445, in readpath
    startDate = string_to_datetime(startDate)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/users/vankova/mpas-analysis/fris_map2/mpas_analysis/shared/timekeeping/utility.py", line 111, in string_to_datetime
    return datetime.datetime(year=year, month=month, day=day, hour=hour,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: year 0 is out of range
Warning: mpasClimatologySeaIceAvg failed during check and will not be run
Warning: prerequisite of climatologyMapSeaIceProductionNH failed during check, so this task will not be run
Traceback (most recent call last):
  File "/users/vankova/mpas-analysis/fris_map2/mpas_analysis/__main__.py", line 445, in add_task_and_subtasks
    analysisTask.setup_and_check()
  File "/users/vankova/mpas-analysis/fris_map2/mpas_analysis/shared/climatology/mpas_climatology_task.py", line 279, in setup_and_check
    self.inputFiles = self.historyStreams.readpath(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/users/vankova/mpas-analysis/fris_map2/mpas_analysis/shared/io/namelist_streams_interface.py", line 445, in readpath
    startDate = string_to_datetime(startDate)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/users/vankova/mpas-analysis/fris_map2/mpas_analysis/shared/timekeeping/utility.py", line 111, in string_to_datetime
    return datetime.datetime(year=year, month=month, day=day, hour=hour,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: year 0 is out of range
Warning: mpasClimatologySeaIceAvg failed during check and will not be run
Warning: prerequisite of climatologyMapSeaIceProductionSH failed during check, so this task will not be run
Traceback (most recent call last):
  File "/users/vankova/mpas-analysis/fris_map2/mpas_analysis/__main__.py", line 445, in add_task_and_subtasks
    analysisTask.setup_and_check()
  File "/users/vankova/mpas-analysis/fris_map2/mpas_analysis/shared/climatology/mpas_climatology_task.py", line 279, in setup_and_check
    self.inputFiles = self.historyStreams.readpath(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/users/vankova/mpas-analysis/fris_map2/mpas_analysis/shared/io/namelist_streams_interface.py", line 445, in readpath
    startDate = string_to_datetime(startDate)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/users/vankova/mpas-analysis/fris_map2/mpas_analysis/shared/timekeeping/utility.py", line 111, in string_to_datetime
    return datetime.datetime(year=year, month=month, day=day, hour=hour,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: year 0 is out of range
Warning: mpasClimatologySeaIceAvg failed during check and will not be run
Warning: prerequisite of climatologyMapSeaIceMeltingNH failed during check, so this task will not be run
Traceback (most recent call last):
  File "/users/vankova/mpas-analysis/fris_map2/mpas_analysis/__main__.py", line 445, in add_task_and_subtasks
    analysisTask.setup_and_check()
  File "/users/vankova/mpas-analysis/fris_map2/mpas_analysis/shared/climatology/mpas_climatology_task.py", line 279, in setup_and_check
    self.inputFiles = self.historyStreams.readpath(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/users/vankova/mpas-analysis/fris_map2/mpas_analysis/shared/io/namelist_streams_interface.py", line 445, in readpath
    startDate = string_to_datetime(startDate)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/users/vankova/mpas-analysis/fris_map2/mpas_analysis/shared/timekeeping/utility.py", line 111, in string_to_datetime
    return datetime.datetime(year=year, month=month, day=day, hour=hour,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: year 0 is out of range
Warning: mpasClimatologySeaIceAvg failed during check and will not be run
Warning: prerequisite of climatologyMapSeaIceMeltingSH failed during check, so this task will not be run
Traceback (most recent call last):
  File "/users/vankova/mpas-analysis/fris_map2/mpas_analysis/__main__.py", line 445, in add_task_and_subtasks
    analysisTask.setup_and_check()
  File "/users/vankova/mpas-analysis/fris_map2/mpas_analysis/shared/time_series/mpas_time_series_task.py", line 174, in setup_and_check
    self.inputFiles = self.historyStreams.readpath(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/users/vankova/mpas-analysis/fris_map2/mpas_analysis/shared/io/namelist_streams_interface.py", line 445, in readpath
    startDate = string_to_datetime(startDate)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/users/vankova/mpas-analysis/fris_map2/mpas_analysis/shared/timekeeping/utility.py", line 111, in string_to_datetime
    return datetime.datetime(year=year, month=month, day=day, hour=hour,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: year 0 is out of range
Warning: mpasTimeSeriesSeaIce failed during check and will not be run
Warning: prerequisite of timeSeriesSeaIceAreaVol failed during check, so this task will not be run

69 tasks and subtasks failed during setup.

Running tasks:   1% |                                          | ETA:   6:41:40
Running tasks:  11% |####                                      | ETA:   0:47:01
ERROR in task timeSeriesTransport: computeTransport_0000-0000.  See log file /lustre/scratch4/turquoise/vankova/E3SM/analysis/chic_test_00_30/clim_0-30_ts_0-30/logs/timeSeriesTransport_computeTransport_0000-0000.log for details
Running tasks:  12% |#####                                     | ETA:   0:51:24
Running tasks:  12% |#####                                     | ETA:   0:49:30
Running tasks:  13% |#####                                     | ETA:   0:45:25
Running tasks:  14% |#####                                     | ETA:   0:43:42
Running tasks:  14% |######                                    | ETA:   0:41:58
Running tasks:  16% |######                                    | ETA:   0:37:30
Running tasks:  17% |#######                                   | ETA:   0:34:54
Running tasks:  18% |#######                                   | ETA:   0:32:37
Running tasks:  76% |###############################           | ETA:   0:02:17
Running tasks:  77% |################################          | ETA:   0:02:06
Running tasks:  79% |#################################         | ETA:   0:01:55
Running tasks:  80% |#################################         | ETA:   0:01:48
Running tasks:  80% |#################################         | ETA:   0:01:48
Running tasks:  80% |#################################         | ETA:   0:01:48
Running tasks:  80% |#################################         | ETA:   0:01:48
Running tasks:  80% |#################################         | ETA:   0:01:49
Running tasks:  80% |#################################         | ETA:   0:01:49
Running tasks:  80% |#################################         | ETA:   0:01:49
Running tasks:  80% |#################################         | ETA:   0:01:49
Running tasks:  80% |#################################         | ETA:   0:01:45
Running tasks:  81% |##################################        | ETA:   0:01:42
Running tasks:  81% |##################################        | ETA:   0:01:42
Running tasks:  81% |##################################        | ETA:   0:01:42
Running tasks:  81% |##################################        | ETA:   0:01:42
ERROR in task oceanRegionalProfiles: computeOceanBasinsProfiles_0000-0000.  See log file /lustre/scratch4/turquoise/vankova/E3SM/analysis/chic_test_00_30/clim_0-30_ts_0-30/logs/oceanRegionalProfiles_computeOceanBasinsProfiles_0000-0000.log for details
Running tasks:  81% |##################################        | ETA:   0:01:39
Running tasks:  82% |##################################        | ETA:   0:01:38
Running tasks:  82% |##################################        | ETA:   0:01:37
Running tasks:  83% |##################################        | ETA:   0:01:35
Running tasks:  83% |###################################       | ETA:   0:01:32
Running tasks:  84% |###################################       | ETA:   0:01:26
Running tasks:  85% |###################################       | ETA:   0:01:51
Running tasks:  85% |####################################      | ETA:   0:01:46
Running tasks:  86% |####################################      | ETA:   0:01:43
Running tasks:  86% |####################################      | ETA:   0:01:39
Running tasks:  87% |####################################      | ETA:   0:01:35
Running tasks:  88% |#####################################     | ETA:   0:01:27
Running tasks:  88% |#####################################     | ETA:   0:01:27
Running tasks:  88% |#####################################     | ETA:   0:01:23
Running tasks:  89% |#####################################     | ETA:   0:01:15
Running tasks:  90% |#####################################     | ETA:   0:01:11
Running tasks:  90% |#####################################     | ETA:   0:01:11
Running tasks:  91% |######################################    | ETA:   0:01:03
Running tasks:  91% |######################################    | ETA:   0:00:59
Running tasks:  93% |#######################################   | ETA:   0:00:47
Running tasks:  94% |#######################################   | ETA:   0:00:40
Running tasks:  94% |#######################################   | ETA:   0:00:36
Running tasks:  95% |########################################  | ETA:   0:00:33
Running tasks:  95% |########################################  | ETA:   0:00:29
Running tasks:  96% |########################################  | ETA:   0:00:25
Running tasks:  96% |########################################  | ETA:   0:00:21
Running tasks:  97% |########################################  | ETA:   0:00:19
Running tasks:  97% |######################################### | ETA:   0:00:16
Running tasks:  98% |######################################### | ETA:   0:00:12
Running tasks:  98% |######################################### | ETA:   0:00:08
Running tasks:  99% |######################################### | ETA:   0:00:04
Running tasks: 100% |##########################################| ETA:  00:00:00
Running tasks: 100% |##########################################| Time:  0:13:51

There were errors in 2 tasks: timeSeriesTransport: computeTransport_0000-0000, oceanRegionalProfiles: computeOceanBasinsProfiles_0000-0000
See log files in /lustre/scratch4/turquoise/vankova/E3SM/analysis/chic_test_00_30/clim_0-30_ts_0-30/logs for details.
The following commands may be helpful:
  cd /lustre/scratch4/turquoise/vankova/E3SM/analysis/chic_test_00_30/clim_0-30_ts_0-30/logs
  grep Error *.log
